import { ApolloProvider } from "@apollo/client";
import { Inter } from "next/font/google";
import Head from "next/head";
import { client } from "../config/apollo";
import { UserProvider } from "../context/user/user.provider";
import withAuth from "../utils/validateAuth";
import BankLoginPage from "../_Pages/BankLogin/BankLoginPage";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Sistema bancario</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApolloProvider client={client()}>
        <UserProvider>
          <BankLoginPage />
        </UserProvider>
      </ApolloProvider>
    </>
  );
};

export default withAuth(Home);
